import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/providers/ReduxProvider";
import { AuthProvider } from "../components/providers/Auth0Provider";
import GlobalAuthProvider from "../components/providers/GlobalAuthProvider";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ReduxProvider>
            <GlobalAuthProvider>
              <Header />
              {children}
            </GlobalAuthProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
